from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any, Iterable


DATASET_NAME = "bigcode/the-stack"
DEFAULT_OUTPUT = Path("the_stack_code_qa.json")
DEFAULT_LANGUAGES = ("python", "javascript", "html", "css")


def clean_text(value: Any) -> str:
    return "\n".join(str(value or "").replace("\r\n", "\n").splitlines()).strip()


def compact_line(text: str, limit: int = 180) -> str:
    line = " ".join(text.strip().split())
    if len(line) <= limit:
        return line
    return line[:limit].rsplit(" ", 1)[0].rstrip() + "..."


def language_from_row(row: dict[str, Any], fallback: str) -> str:
    for key in ("lang", "language", "ext"):
        value = str(row.get(key, "")).strip().lower()
        if value:
            return value
    return fallback


def code_from_row(row: dict[str, Any]) -> str:
    for key in ("content", "text", "code"):
        value = clean_text(row.get(key))
        if value:
            return value
    return ""


def interesting_code(code: str, min_chars: int, max_chars: int) -> bool:
    if not (min_chars <= len(code) <= max_chars):
        return False
    lowered = code.lower()
    if "generated by" in lowered or "minified" in lowered:
        return False
    lines = [line for line in code.splitlines() if line.strip()]
    if len(lines) < 3:
        return False
    long_lines = sum(1 for line in lines if len(line) > 220)
    return long_lines <= max(2, len(lines) // 4)


def extract_title(code: str, language: str, index: int) -> str:
    patterns = {
        "python": r"^\s*(?:def|class)\s+([A-Za-z_][\w]*)",
        "javascript": r"^\s*(?:function\s+([A-Za-z_$][\w$]*)|(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=)",
        "typescript": r"^\s*(?:function\s+([A-Za-z_$][\w$]*)|(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=)",
        "html": r"<\s*(main|section|form|article|nav|header|footer)\b",
        "css": r"^\s*([.#]?[A-Za-z][\w-]*)\s*\{",
    }
    pattern = patterns.get(language)
    if pattern:
        match = re.search(pattern, code, flags=re.MULTILINE | re.IGNORECASE)
        if match:
            name = next((group for group in match.groups() if group), match.group(0))
            return compact_line(str(name), 80)
    first = next((line.strip() for line in code.splitlines() if line.strip()), "")
    return compact_line(first or f"exemple {index}", 80)


def build_answer(code: str, language: str, title: str) -> str:
    snippet = code.strip()
    if len(snippet) > 1800:
        snippet = snippet[:1800].rsplit("\n", 1)[0].rstrip() + "\n..."
    return (
        f"C'est un exemple de code {language}. "
        f"Point principal: {title}.\n"
        "Pour l'analyser, lis d'abord les entrees, puis les transformations, puis la sortie.\n"
        f"Code:\n```{language}\n{snippet}\n```"
    )


def row_to_examples(row: dict[str, Any], language: str, index: int) -> list[dict[str, str]]:
    code = code_from_row(row)
    if not interesting_code(code, min_chars=120, max_chars=5000):
        return []
    title = extract_title(code, language, index)
    answer = build_answer(code, language, title)
    return [
        {
            "question": f"explique ce code {language}: {title}",
            "answer": answer,
        },
        {
            "question": f"que fait cet exemple {language}: {title}",
            "answer": answer,
        },
    ]


def stream_language(language: str, split: str) -> Iterable[dict[str, Any]]:
    from datasets import load_dataset

    token = True if os.getenv("HF_TOKEN") else None
    return load_dataset(
        DATASET_NAME,
        data_dir=f"data/{language}",
        split=split,
        streaming=True,
        token=token,
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Cree un petit fichier QA Lucie depuis bigcode/the-stack sans telecharger tout le dataset."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--limit", type=int, default=500, help="Nombre maximum de questions/reponses.")
    parser.add_argument("--per-language", type=int, default=150, help="Maximum par langage.")
    parser.add_argument("--split", default="train")
    parser.add_argument(
        "--languages",
        default=",".join(DEFAULT_LANGUAGES),
        help="Langages separes par virgules, ex: python,javascript,html,css",
    )
    args = parser.parse_args()

    try:
        import datasets  # noqa: F401
    except ImportError as exc:
        raise SystemExit("Installe d'abord: python -m pip install datasets") from exc

    examples: list[dict[str, str]] = []
    seen: set[str] = set()
    languages = [item.strip().lower() for item in args.languages.split(",") if item.strip()]

    for language in languages:
        language_count = 0
        try:
            dataset = stream_language(language, args.split)
            for index, row in enumerate(dataset, start=1):
                if not isinstance(row, dict):
                    continue
                row_language = language_from_row(row, language)
                for example in row_to_examples(row, row_language, index):
                    key = example["question"].lower()
                    if key in seen:
                        continue
                    seen.add(key)
                    examples.append(example)
                    language_count += 1
                    if len(examples) >= args.limit or language_count >= args.per_language:
                        break
                if len(examples) >= args.limit or language_count >= args.per_language:
                    break
        except Exception as exc:
            print(f"Attention: impossible de lire {language}: {exc}")
        if len(examples) >= args.limit:
            break

    args.output.write_text(
        json.dumps(examples, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"OK: {len(examples)} exemples The Stack ecrits dans {args.output}")


if __name__ == "__main__":
    main()
